name: LayoutSpecs

targets:
  LayoutSpecs:
    name: LayoutSpecs
    platform: iOS
    type: application
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: dev.huynguyen.LayoutSpecs
    sources:
      - path: Source
        name: App
        includes:
          - "**./*.h"
          - "**./*.m"
          - "**./*.mm"
